language: java

dist: trusty

jdk:
  - oraclejdk8

install: ./gradlew build --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "kbTpvi/gXysGXSxrG0/GSQ9zOmNNMIiHM2nPpPXK9y78SFqubG2EEHnyjNYPfjMUPtnW/X+N29gu74ycI0XfHLRO7MTBGBzbtoxmfP9ONqngRkrUJuBWrSpqQZgSafDA+16Xs8WiZa3wqH1BPHvNSS07b8lHZPLJlQn7sRU+gRV0XTP3EEFmR5R0+A109HorVX1qR/YlDotuYak2/3Y40ERCasGntkLuxJbgU9dSAUZ3WIS+r+nsg5WKEwr9o5kq35Gfi9Y290gRe0iasotJsGpD/o5lsDo157VtakU2IpdmzrbL4FLCXD9nuS7lttyYcDk3VnVjUzlobe6yBSchDtFBKsdlqi0REbPXycs5THLoW4ROzGq0mpMhbDl1E4H36nH6gWh0CxwCqgcgode2li/W1BwJ2XEafZSZNN/k9OkAmovNdRzdVu3mN5IuKK7mo8xJ/gQiqYMvPDxm2PbgvZvzW09EaNxTtHfhG+32jD4mAxAYj5ml2WrLT8Fwp9zrR0BaBsIouUn1QHAY7LOf3+gMOH1stkEFluOGhKPflY1t6EanOulapfmbn/kaDq2j/sFwAZocxAFt8K10c8cnIstxGPKhf7BtuI58cdCK0z+qqmzRL5OPDIh/rkOcvLslMxCUXpaOfV894d6KgXL/5UG8EUosf4t7RB/QgGYe5ow="
    - secure: "GYtPEU6XREHdXTaJDnY3cPVxtHpC+0FUogLGciqbQVHcQMtUC0bRyUx3JgWPtdmMnTqesDabYx7u7YfJ2QINZW+2FEZ1CYsZl64Kvgco0b6N6t1jSQLHjJ8e1X80JWKrZ9OtTQMH4NRihKGKPDzXOuLSA7hxLmKVGOX6HgbHq1E3z7EMUVmQ689QELfBaHNJRyQZeA7NfFWKuTKHHlLzZlU/91iuCcN7mQ/4M7ENta4kYDpOhVRfUQB/QTTvGF63w1VbJkkBd8re1XXN1C1mjsb5JTvv6igt0AdgRIAhh3EtAQO5SiU1eT3LSxNwsYjtk33j6hbTXq1Ikmgs7UR9ghIU9//VUgLniwJiZp9TKKkY2UovFdEhgLGBisdsy0us2oom2rkB3gd0nVCA1bB8dXBYZlRTnhEHGMSa/YcTQIH2svp64x+UYg2cdmMsukWwMJgVhTFfuPxQUKs9zIiXhX+it0/BLF3oiGxYWYNeKhr/NCgh7wYo7qhq3S7e+3CDY1h3m7IhHcNRqgH5wr3q8PindV87tZgXwG1hPgl7In7wynKUOAXGoIm+V9dVpG1sCW+8TxGBZvF+2dD95p4yO6ucVQIJbHQtqvAI+5bZYE3tWOcSZ2l038jSSkSpCP2qvDxN0C//K1LMSjxBUQIVNdtMaUwxylP2qAJelUc55eI="

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
